// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type ReactionServiceReaction struct {
	VideoId string
	UserId  string
	Kind    string
	AddedAt time.Time
}

type ReactionServiceView struct {
	VideoId   string
	UserId    string
	CreatedAt time.Time
}
