// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type ReactionServiceView struct {
	VideoId   string
	UserId    string
	CreatedAt time.Time
}
