// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type ReactionServiceComment struct {
	Id        uuid.UUID
	VideoId   uuid.UUID
	OwnerId   uuid.UUID
	Content   string
	CreatedAt time.Time
	ParentId  uuid.NullUUID
}

type ReactionServiceReaction struct {
	VideoId uuid.UUID
	UserId  uuid.UUID
	Kind    string
	AddedAt time.Time
}

type ReactionServiceView struct {
	VideoId   uuid.UUID
	UserId    uuid.UUID
	CreatedAt time.Time
}
