// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const getViewsCount = `-- name: GetViewsCount :one
select count(*) from reaction_service.views where video_id = $1
`

func (q *Queries) GetViewsCount(ctx context.Context, videoID string) (int64, error) {
	row := q.queryRow(ctx, q.getViewsCountStmt, getViewsCount, videoID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertView = `-- name: InsertView :execrows
insert into reaction_service.views (video_id, user_id) values ($1, $2)
on conflict (video_id, user_id) do nothing
`

type InsertViewParams struct {
	VideoId string
	UserId  string
}

func (q *Queries) InsertView(ctx context.Context, arg InsertViewParams) (int64, error) {
	result, err := q.exec(ctx, q.insertViewStmt, insertView, arg.VideoId, arg.UserId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
