// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.batchDeleteExpiredEmailVerificationTokensStmt, err = db.PrepareContext(ctx, batchDeleteExpiredEmailVerificationTokens); err != nil {
		return nil, fmt.Errorf("error preparing query BatchDeleteExpiredEmailVerificationTokens: %w", err)
	}
	if q.batchDeleteExpiredSessionsStmt, err = db.PrepareContext(ctx, batchDeleteExpiredSessions); err != nil {
		return nil, fmt.Errorf("error preparing query BatchDeleteExpiredSessions: %w", err)
	}
	if q.checkEmailStmt, err = db.PrepareContext(ctx, checkEmail); err != nil {
		return nil, fmt.Errorf("error preparing query CheckEmail: %w", err)
	}
	if q.checkUsernameStmt, err = db.PrepareContext(ctx, checkUsername); err != nil {
		return nil, fmt.Errorf("error preparing query CheckUsername: %w", err)
	}
	if q.deleteAllEmailVerificationTokensForUserStmt, err = db.PrepareContext(ctx, deleteAllEmailVerificationTokensForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllEmailVerificationTokensForUser: %w", err)
	}
	if q.deleteAllSessionsForUserStmt, err = db.PrepareContext(ctx, deleteAllSessionsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllSessionsForUser: %w", err)
	}
	if q.deleteSessionForUserStmt, err = db.PrepareContext(ctx, deleteSessionForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionForUser: %w", err)
	}
	if q.getSessionByIdStmt, err = db.PrepareContext(ctx, getSessionById); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionById: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIdStmt, err = db.PrepareContext(ctx, getUserById); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserById: %w", err)
	}
	if q.getUserByUsernameStmt, err = db.PrepareContext(ctx, getUserByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByUsername: %w", err)
	}
	if q.insertEmailVerificationTokenStmt, err = db.PrepareContext(ctx, insertEmailVerificationToken); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEmailVerificationToken: %w", err)
	}
	if q.insertSessionStmt, err = db.PrepareContext(ctx, insertSession); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSession: %w", err)
	}
	if q.insertUserStmt, err = db.PrepareContext(ctx, insertUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUser: %w", err)
	}
	if q.softDeleteUserByIdStmt, err = db.PrepareContext(ctx, softDeleteUserById); err != nil {
		return nil, fmt.Errorf("error preparing query SoftDeleteUserById: %w", err)
	}
	if q.updateProfileStmt, err = db.PrepareContext(ctx, updateProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateProfile: %w", err)
	}
	if q.verifyEmailByTokenStmt, err = db.PrepareContext(ctx, verifyEmailByToken); err != nil {
		return nil, fmt.Errorf("error preparing query VerifyEmailByToken: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.batchDeleteExpiredEmailVerificationTokensStmt != nil {
		if cerr := q.batchDeleteExpiredEmailVerificationTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing batchDeleteExpiredEmailVerificationTokensStmt: %w", cerr)
		}
	}
	if q.batchDeleteExpiredSessionsStmt != nil {
		if cerr := q.batchDeleteExpiredSessionsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing batchDeleteExpiredSessionsStmt: %w", cerr)
		}
	}
	if q.checkEmailStmt != nil {
		if cerr := q.checkEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkEmailStmt: %w", cerr)
		}
	}
	if q.checkUsernameStmt != nil {
		if cerr := q.checkUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkUsernameStmt: %w", cerr)
		}
	}
	if q.deleteAllEmailVerificationTokensForUserStmt != nil {
		if cerr := q.deleteAllEmailVerificationTokensForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllEmailVerificationTokensForUserStmt: %w", cerr)
		}
	}
	if q.deleteAllSessionsForUserStmt != nil {
		if cerr := q.deleteAllSessionsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllSessionsForUserStmt: %w", cerr)
		}
	}
	if q.deleteSessionForUserStmt != nil {
		if cerr := q.deleteSessionForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionForUserStmt: %w", cerr)
		}
	}
	if q.getSessionByIdStmt != nil {
		if cerr := q.getSessionByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIdStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIdStmt != nil {
		if cerr := q.getUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIdStmt: %w", cerr)
		}
	}
	if q.getUserByUsernameStmt != nil {
		if cerr := q.getUserByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByUsernameStmt: %w", cerr)
		}
	}
	if q.insertEmailVerificationTokenStmt != nil {
		if cerr := q.insertEmailVerificationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEmailVerificationTokenStmt: %w", cerr)
		}
	}
	if q.insertSessionStmt != nil {
		if cerr := q.insertSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionStmt: %w", cerr)
		}
	}
	if q.insertUserStmt != nil {
		if cerr := q.insertUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserStmt: %w", cerr)
		}
	}
	if q.softDeleteUserByIdStmt != nil {
		if cerr := q.softDeleteUserByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing softDeleteUserByIdStmt: %w", cerr)
		}
	}
	if q.updateProfileStmt != nil {
		if cerr := q.updateProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateProfileStmt: %w", cerr)
		}
	}
	if q.verifyEmailByTokenStmt != nil {
		if cerr := q.verifyEmailByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifyEmailByTokenStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                            DBTX
	tx                                            *sql.Tx
	batchDeleteExpiredEmailVerificationTokensStmt *sql.Stmt
	batchDeleteExpiredSessionsStmt                *sql.Stmt
	checkEmailStmt                                *sql.Stmt
	checkUsernameStmt                             *sql.Stmt
	deleteAllEmailVerificationTokensForUserStmt   *sql.Stmt
	deleteAllSessionsForUserStmt                  *sql.Stmt
	deleteSessionForUserStmt                      *sql.Stmt
	getSessionByIdStmt                            *sql.Stmt
	getUserByEmailStmt                            *sql.Stmt
	getUserByIdStmt                               *sql.Stmt
	getUserByUsernameStmt                         *sql.Stmt
	insertEmailVerificationTokenStmt              *sql.Stmt
	insertSessionStmt                             *sql.Stmt
	insertUserStmt                                *sql.Stmt
	softDeleteUserByIdStmt                        *sql.Stmt
	updateProfileStmt                             *sql.Stmt
	verifyEmailByTokenStmt                        *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
		tx: tx,
		batchDeleteExpiredEmailVerificationTokensStmt: q.batchDeleteExpiredEmailVerificationTokensStmt,
		batchDeleteExpiredSessionsStmt:                q.batchDeleteExpiredSessionsStmt,
		checkEmailStmt:                                q.checkEmailStmt,
		checkUsernameStmt:                             q.checkUsernameStmt,
		deleteAllEmailVerificationTokensForUserStmt:   q.deleteAllEmailVerificationTokensForUserStmt,
		deleteAllSessionsForUserStmt:                  q.deleteAllSessionsForUserStmt,
		deleteSessionForUserStmt:                      q.deleteSessionForUserStmt,
		getSessionByIdStmt:                            q.getSessionByIdStmt,
		getUserByEmailStmt:                            q.getUserByEmailStmt,
		getUserByIdStmt:                               q.getUserByIdStmt,
		getUserByUsernameStmt:                         q.getUserByUsernameStmt,
		insertEmailVerificationTokenStmt:              q.insertEmailVerificationTokenStmt,
		insertSessionStmt:                             q.insertSessionStmt,
		insertUserStmt:                                q.insertUserStmt,
		softDeleteUserByIdStmt:                        q.softDeleteUserByIdStmt,
		updateProfileStmt:                             q.updateProfileStmt,
		verifyEmailByTokenStmt:                        q.verifyEmailByTokenStmt,
	}
}
