// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"
)

type UserServiceEmailVerificationToken struct {
	ID        string
	OwnerID   string
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type UserServiceSession struct {
	ID           string
	OwnerID      string
	SessionToken string
	CsrfToken    string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type UserServiceUser struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	Username     string
	CreatedAt    time.Time
	IsVerified   bool
}
