// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type UserServiceEmailVerificationToken struct {
	Id        string
	OwnerId   string
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type UserServiceSession struct {
	Id           string
	OwnerId      string
	SessionToken string
	CsrfToken    string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type UserServiceUser struct {
	Id           string
	Email        string
	PasswordHash string
	Name         string
	Username     string
	Bio          sql.NullString
	CreatedAt    time.Time
	IsVerified   bool
}
