// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type UserServiceEmailVerificationToken struct {
	Id        uuid.UUID
	OwnerId   uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type UserServiceSession struct {
	Id           uuid.UUID
	OwnerId      uuid.UUID
	SessionToken string
	CsrfToken    string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type UserServiceUser struct {
	Id           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Username     string
	Bio          sql.NullString
	CreatedAt    time.Time
	IsVerified   bool
	IsDeleted    bool
}
