// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const batchDeleteExpiredEmailVerificationTokens = `-- name: BatchDeleteExpiredEmailVerificationTokens :exec
do $$
declare
  rows_deleted int;
begin
  loop
    delete from user_service.email_verification_tokens
    where ctid in (
      select ctid
      from user_service.email_verification_tokens
      where expires_at <= now()
      limit 1000
    );
    get diagnostics rows_deleted = row_count;
    exit when rows_deleted = 0;
  end loop;
end
$$
`

func (q *Queries) BatchDeleteExpiredEmailVerificationTokens(ctx context.Context) error {
	_, err := q.exec(ctx, q.batchDeleteExpiredEmailVerificationTokensStmt, batchDeleteExpiredEmailVerificationTokens)
	return err
}

const batchDeleteExpiredSessions = `-- name: BatchDeleteExpiredSessions :exec
do $$
declare
  rows_deleted int;
begin
  loop
    delete from user_service.sessions
    where ctid in (
      select ctid
      from user_service.sessions
      where expires_at <= now()
      limit 1000
    );
    get diagnostics rows_deleted = row_count;
    exit when rows_deleted = 0;
  end loop;
end
$$
`

func (q *Queries) BatchDeleteExpiredSessions(ctx context.Context) error {
	_, err := q.exec(ctx, q.batchDeleteExpiredSessionsStmt, batchDeleteExpiredSessions)
	return err
}

const checkEmail = `-- name: CheckEmail :one
select exists (select 1 from user_service.users where email = $1 and is_deleted = false for update)
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.checkEmailStmt, checkEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsername = `-- name: CheckUsername :one
select exists (select 1 from user_service.users where username = $1 for update)
`

// Don't check for is_deleted. Username can only be aquired once.
// We don't need unexpected profiles when navigating a url.
func (q *Queries) CheckUsername(ctx context.Context, username string) (bool, error) {
	row := q.queryRow(ctx, q.checkUsernameStmt, checkUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAllEmailVerificationTokensForUser = `-- name: DeleteAllEmailVerificationTokensForUser :exec
delete from user_service.email_verification_tokens where owner_id = $1 and expires_at > now()
`

func (q *Queries) DeleteAllEmailVerificationTokensForUser(ctx context.Context, ownerID string) error {
	_, err := q.exec(ctx, q.deleteAllEmailVerificationTokensForUserStmt, deleteAllEmailVerificationTokensForUser, ownerID)
	return err
}

const deleteAllSessionsForUser = `-- name: DeleteAllSessionsForUser :exec
delete from user_service.sessions where owner_id = $1 and expires_at > now()
`

func (q *Queries) DeleteAllSessionsForUser(ctx context.Context, ownerID string) error {
	_, err := q.exec(ctx, q.deleteAllSessionsForUserStmt, deleteAllSessionsForUser, ownerID)
	return err
}

const deleteSessionForUser = `-- name: DeleteSessionForUser :execrows
delete from user_service.sessions where id = $1 and owner_id = $2
`

type DeleteSessionForUserParams struct {
	SessionId string
	UserId    string
}

func (q *Queries) DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionForUserStmt, deleteSessionForUser, arg.SessionId, arg.UserId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionById = `-- name: GetSessionById :one
select id, owner_id, session_token, csrf_token, created_at, expires_at from user_service.sessions where id = $1
`

func (q *Queries) GetSessionById(ctx context.Context, id string) (UserServiceSession, error) {
	row := q.queryRow(ctx, q.getSessionByIdStmt, getSessionById, id)
	var i UserServiceSession
	err := row.Scan(
		&i.Id,
		&i.OwnerId,
		&i.SessionToken,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, name, username, bio, created_at, is_verified, is_deleted from user_service.users where email = $1 and is_deleted = false for update
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserServiceUser, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i UserServiceUser
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Username,
		&i.Bio,
		&i.CreatedAt,
		&i.IsVerified,
		&i.IsDeleted,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
select id, email, password_hash, name, username, bio, created_at, is_verified, is_deleted from user_service.users where id = $1 and is_deleted = false for update
`

func (q *Queries) GetUserById(ctx context.Context, id string) (UserServiceUser, error) {
	row := q.queryRow(ctx, q.getUserByIdStmt, getUserById, id)
	var i UserServiceUser
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Username,
		&i.Bio,
		&i.CreatedAt,
		&i.IsVerified,
		&i.IsDeleted,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, email, password_hash, name, username, bio, created_at, is_verified, is_deleted from user_service.users where username = $1 and is_deleted = false for update
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (UserServiceUser, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i UserServiceUser
	err := row.Scan(
		&i.Id,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Username,
		&i.Bio,
		&i.CreatedAt,
		&i.IsVerified,
		&i.IsDeleted,
	)
	return i, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
insert into user_service.email_verification_tokens (id, owner_id, token, expires_at)
values ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	Id        string
	OwnerId   string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.exec(ctx, q.insertEmailVerificationTokenStmt, insertEmailVerificationToken,
		arg.Id,
		arg.OwnerId,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
insert into user_service.sessions (id, owner_id, session_token, csrf_token, expires_at)
values ($1, $2, $3, $4, $5)
`

type InsertSessionParams struct {
	Id           string
	OwnerId      string
	SessionToken string
	CsrfToken    string
	ExpiresAt    time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.exec(ctx, q.insertSessionStmt, insertSession,
		arg.Id,
		arg.OwnerId,
		arg.SessionToken,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
insert into user_service.users (id, email, password_hash, name, username, bio)
values ($1, $2, $3, $4, $5, $6)
`

type InsertUserParams struct {
	Id           string
	Email        string
	PasswordHash string
	Name         string
	Username     string
	Bio          sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.exec(ctx, q.insertUserStmt, insertUser,
		arg.Id,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Username,
		arg.Bio,
	)
	return err
}

const softDeleteUserById = `-- name: SoftDeleteUserById :execrows
update user_service.users set is_deleted = true where id = $1
`

func (q *Queries) SoftDeleteUserById(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.softDeleteUserByIdStmt, softDeleteUserById, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateProfile = `-- name: UpdateProfile :exec
update user_service.users
set
  name = $1,
  username = $2,
  bio = $3
where id = $4
`

type UpdateProfileParams struct {
	Name     string
	Username string
	Bio      sql.NullString
	UserId   string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.exec(ctx, q.updateProfileStmt, updateProfile,
		arg.Name,
		arg.Username,
		arg.Bio,
		arg.UserId,
	)
	return err
}

const verifyEmailByToken = `-- name: VerifyEmailByToken :execrows
update user_service.users
set is_verified = true
where id in (
  select owner_id
  from user_service.email_verification_tokens evt
  where token = $1 and expires_at > now()
)
`

func (q *Queries) VerifyEmailByToken(ctx context.Context, token string) (int64, error) {
	result, err := q.exec(ctx, q.verifyEmailByTokenStmt, verifyEmailByToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
