// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const checkEmail = `-- name: CheckEmail :one
select exists (select 1 from user_service.users where email = $1 for update)
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.checkEmailStmt, checkEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkUsername = `-- name: CheckUsername :one
select exists (select 1 from user_service.users where username = $1 for update)
`

func (q *Queries) CheckUsername(ctx context.Context, username string) (bool, error) {
	row := q.queryRow(ctx, q.checkUsernameStmt, checkUsername, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteSessionForUser = `-- name: DeleteSessionForUser :execrows
delete from user_service.sessions where id = $1 and owner_id = $2
`

type DeleteSessionForUserParams struct {
	SessionID string
	UserID    string
}

func (q *Queries) DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionForUserStmt, deleteSessionForUser, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUser = `-- name: DeleteUser :execrows
delete from user_service.users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByID = `-- name: GetSessionByID :one
select id, owner_id, session_token, csrf_token, created_at, expires_at from user_service.sessions where id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (UserServiceSession, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i UserServiceSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SessionToken,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, name, username, created_at, is_verified, bio from user_service.users where email = $1 for update
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (UserServiceUser, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.IsVerified,
		&i.Bio,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, email, password_hash, name, username, created_at, is_verified, bio from user_service.users where id = $1 for update
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (UserServiceUser, error) {
	row := q.queryRow(ctx, q.getUserByIDStmt, getUserByID, id)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.IsVerified,
		&i.Bio,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, email, password_hash, name, username, created_at, is_verified, bio from user_service.users where username = $1 for update
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (UserServiceUser, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Username,
		&i.CreatedAt,
		&i.IsVerified,
		&i.Bio,
	)
	return i, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
insert into user_service.email_verification_tokens (id, owner_id, token, expires_at)
values ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	ID        string
	OwnerID   string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.exec(ctx, q.insertEmailVerificationTokenStmt, insertEmailVerificationToken,
		arg.ID,
		arg.OwnerID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
insert into user_service.sessions (id, owner_id, session_token, csrf_token, expires_at)
values ($1, $2, $3, $4, $5)
`

type InsertSessionParams struct {
	ID           string
	OwnerID      string
	SessionToken string
	CsrfToken    string
	ExpiresAt    time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.exec(ctx, q.insertSessionStmt, insertSession,
		arg.ID,
		arg.OwnerID,
		arg.SessionToken,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
insert into user_service.users (id, email, password_hash, name, username, bio)
values ($1, $2, $3, $4, $5, $6)
`

type InsertUserParams struct {
	ID           string
	Email        string
	PasswordHash string
	Name         string
	Username     string
	Bio          sql.NullString
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.exec(ctx, q.insertUserStmt, insertUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Username,
		arg.Bio,
	)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
update user_service.users
set
  name = $1,
  username = $2,
  bio = $3
where id = $4
`

type UpdateProfileParams struct {
	Name     string
	Username string
	Bio      sql.NullString
	UserID   string
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.exec(ctx, q.updateProfileStmt, updateProfile,
		arg.Name,
		arg.Username,
		arg.Bio,
		arg.UserID,
	)
	return err
}

const verifyEmailByToken = `-- name: VerifyEmailByToken :execrows
update user_service.users
set is_verified = true
where id in (
  select owner_id
  from user_service.email_verification_tokens evt
  where token = $1 and expires_at > now()
)
`

func (q *Queries) VerifyEmailByToken(ctx context.Context, token string) (int64, error) {
	result, err := q.exec(ctx, q.verifyEmailByTokenStmt, verifyEmailByToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
