// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.getVideoByIdStmt, err = db.PrepareContext(ctx, getVideoById); err != nil {
		return nil, fmt.Errorf("error preparing query GetVideoById: %w", err)
	}
	if q.getVideosForUserStmt, err = db.PrepareContext(ctx, getVideosForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetVideosForUser: %w", err)
	}
	if q.insertVideoStmt, err = db.PrepareContext(ctx, insertVideo); err != nil {
		return nil, fmt.Errorf("error preparing query InsertVideo: %w", err)
	}
	if q.updateVideoStatusStmt, err = db.PrepareContext(ctx, updateVideoStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateVideoStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.getVideoByIdStmt != nil {
		if cerr := q.getVideoByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVideoByIdStmt: %w", cerr)
		}
	}
	if q.getVideosForUserStmt != nil {
		if cerr := q.getVideosForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVideosForUserStmt: %w", cerr)
		}
	}
	if q.insertVideoStmt != nil {
		if cerr := q.insertVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertVideoStmt: %w", cerr)
		}
	}
	if q.updateVideoStatusStmt != nil {
		if cerr := q.updateVideoStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateVideoStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                    DBTX
	tx                    *sql.Tx
	getVideoByIdStmt      *sql.Stmt
	getVideosForUserStmt  *sql.Stmt
	insertVideoStmt       *sql.Stmt
	updateVideoStatusStmt *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                    tx,
		tx:                    tx,
		getVideoByIdStmt:      q.getVideoByIdStmt,
		getVideosForUserStmt:  q.getVideosForUserStmt,
		insertVideoStmt:       q.insertVideoStmt,
		updateVideoStatusStmt: q.updateVideoStatusStmt,
	}
}
