// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkPlaylistStmt, err = db.PrepareContext(ctx, checkPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query CheckPlaylist: %w", err)
	}
	if q.checkPlaylistByNameForUserStmt, err = db.PrepareContext(ctx, checkPlaylistByNameForUser); err != nil {
		return nil, fmt.Errorf("error preparing query CheckPlaylistByNameForUser: %w", err)
	}
	if q.checkPlaylistForUserStmt, err = db.PrepareContext(ctx, checkPlaylistForUser); err != nil {
		return nil, fmt.Errorf("error preparing query CheckPlaylistForUser: %w", err)
	}
	if q.checkVideoStmt, err = db.PrepareContext(ctx, checkVideo); err != nil {
		return nil, fmt.Errorf("error preparing query CheckVideo: %w", err)
	}
	if q.checkVideoInPlaylistStmt, err = db.PrepareContext(ctx, checkVideoInPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query CheckVideoInPlaylist: %w", err)
	}
	if q.checkVideoInWatchlatersStmt, err = db.PrepareContext(ctx, checkVideoInWatchlaters); err != nil {
		return nil, fmt.Errorf("error preparing query CheckVideoInWatchlaters: %w", err)
	}
	if q.deleteAllPlaylistsForUserStmt, err = db.PrepareContext(ctx, deleteAllPlaylistsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllPlaylistsForUser: %w", err)
	}
	if q.deleteAllVideosForUserStmt, err = db.PrepareContext(ctx, deleteAllVideosForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllVideosForUser: %w", err)
	}
	if q.deleteAllWatchlatersForUserStmt, err = db.PrepareContext(ctx, deleteAllWatchlatersForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteAllWatchlatersForUser: %w", err)
	}
	if q.deleteFromWatchlatersStmt, err = db.PrepareContext(ctx, deleteFromWatchlaters); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFromWatchlaters: %w", err)
	}
	if q.deletePlaylistStmt, err = db.PrepareContext(ctx, deletePlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query DeletePlaylist: %w", err)
	}
	if q.deleteVdieoByIdForUserStmt, err = db.PrepareContext(ctx, deleteVdieoByIdForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVdieoByIdForUser: %w", err)
	}
	if q.deleteVideoFromPlaylistStmt, err = db.PrepareContext(ctx, deleteVideoFromPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteVideoFromPlaylist: %w", err)
	}
	if q.getAllPlaylistsForUserStmt, err = db.PrepareContext(ctx, getAllPlaylistsForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllPlaylistsForUser: %w", err)
	}
	if q.getAllVideosForUserStmt, err = db.PrepareContext(ctx, getAllVideosForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllVideosForUser: %w", err)
	}
	if q.getAllVideosInPlaylistStmt, err = db.PrepareContext(ctx, getAllVideosInPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllVideosInPlaylist: %w", err)
	}
	if q.getAllVideosInWatchlatersForUserStmt, err = db.PrepareContext(ctx, getAllVideosInWatchlatersForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetAllVideosInWatchlatersForUser: %w", err)
	}
	if q.getPlaylistForUserStmt, err = db.PrepareContext(ctx, getPlaylistForUser); err != nil {
		return nil, fmt.Errorf("error preparing query GetPlaylistForUser: %w", err)
	}
	if q.getVideoByIdStmt, err = db.PrepareContext(ctx, getVideoById); err != nil {
		return nil, fmt.Errorf("error preparing query GetVideoById: %w", err)
	}
	if q.insertIntoPlaylistStmt, err = db.PrepareContext(ctx, insertIntoPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query InsertIntoPlaylist: %w", err)
	}
	if q.insertIntoWatchlatersStmt, err = db.PrepareContext(ctx, insertIntoWatchlaters); err != nil {
		return nil, fmt.Errorf("error preparing query InsertIntoWatchlaters: %w", err)
	}
	if q.insertPlaylistStmt, err = db.PrepareContext(ctx, insertPlaylist); err != nil {
		return nil, fmt.Errorf("error preparing query InsertPlaylist: %w", err)
	}
	if q.insertVideoStmt, err = db.PrepareContext(ctx, insertVideo); err != nil {
		return nil, fmt.Errorf("error preparing query InsertVideo: %w", err)
	}
	if q.updateVideoStatusStmt, err = db.PrepareContext(ctx, updateVideoStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateVideoStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkPlaylistStmt != nil {
		if cerr := q.checkPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkPlaylistStmt: %w", cerr)
		}
	}
	if q.checkPlaylistByNameForUserStmt != nil {
		if cerr := q.checkPlaylistByNameForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkPlaylistByNameForUserStmt: %w", cerr)
		}
	}
	if q.checkPlaylistForUserStmt != nil {
		if cerr := q.checkPlaylistForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkPlaylistForUserStmt: %w", cerr)
		}
	}
	if q.checkVideoStmt != nil {
		if cerr := q.checkVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkVideoStmt: %w", cerr)
		}
	}
	if q.checkVideoInPlaylistStmt != nil {
		if cerr := q.checkVideoInPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkVideoInPlaylistStmt: %w", cerr)
		}
	}
	if q.checkVideoInWatchlatersStmt != nil {
		if cerr := q.checkVideoInWatchlatersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkVideoInWatchlatersStmt: %w", cerr)
		}
	}
	if q.deleteAllPlaylistsForUserStmt != nil {
		if cerr := q.deleteAllPlaylistsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllPlaylistsForUserStmt: %w", cerr)
		}
	}
	if q.deleteAllVideosForUserStmt != nil {
		if cerr := q.deleteAllVideosForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllVideosForUserStmt: %w", cerr)
		}
	}
	if q.deleteAllWatchlatersForUserStmt != nil {
		if cerr := q.deleteAllWatchlatersForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteAllWatchlatersForUserStmt: %w", cerr)
		}
	}
	if q.deleteFromWatchlatersStmt != nil {
		if cerr := q.deleteFromWatchlatersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFromWatchlatersStmt: %w", cerr)
		}
	}
	if q.deletePlaylistStmt != nil {
		if cerr := q.deletePlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deletePlaylistStmt: %w", cerr)
		}
	}
	if q.deleteVdieoByIdForUserStmt != nil {
		if cerr := q.deleteVdieoByIdForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVdieoByIdForUserStmt: %w", cerr)
		}
	}
	if q.deleteVideoFromPlaylistStmt != nil {
		if cerr := q.deleteVideoFromPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteVideoFromPlaylistStmt: %w", cerr)
		}
	}
	if q.getAllPlaylistsForUserStmt != nil {
		if cerr := q.getAllPlaylistsForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllPlaylistsForUserStmt: %w", cerr)
		}
	}
	if q.getAllVideosForUserStmt != nil {
		if cerr := q.getAllVideosForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllVideosForUserStmt: %w", cerr)
		}
	}
	if q.getAllVideosInPlaylistStmt != nil {
		if cerr := q.getAllVideosInPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllVideosInPlaylistStmt: %w", cerr)
		}
	}
	if q.getAllVideosInWatchlatersForUserStmt != nil {
		if cerr := q.getAllVideosInWatchlatersForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAllVideosInWatchlatersForUserStmt: %w", cerr)
		}
	}
	if q.getPlaylistForUserStmt != nil {
		if cerr := q.getPlaylistForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getPlaylistForUserStmt: %w", cerr)
		}
	}
	if q.getVideoByIdStmt != nil {
		if cerr := q.getVideoByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getVideoByIdStmt: %w", cerr)
		}
	}
	if q.insertIntoPlaylistStmt != nil {
		if cerr := q.insertIntoPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertIntoPlaylistStmt: %w", cerr)
		}
	}
	if q.insertIntoWatchlatersStmt != nil {
		if cerr := q.insertIntoWatchlatersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertIntoWatchlatersStmt: %w", cerr)
		}
	}
	if q.insertPlaylistStmt != nil {
		if cerr := q.insertPlaylistStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertPlaylistStmt: %w", cerr)
		}
	}
	if q.insertVideoStmt != nil {
		if cerr := q.insertVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertVideoStmt: %w", cerr)
		}
	}
	if q.updateVideoStatusStmt != nil {
		if cerr := q.updateVideoStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateVideoStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                   DBTX
	tx                                   *sql.Tx
	checkPlaylistStmt                    *sql.Stmt
	checkPlaylistByNameForUserStmt       *sql.Stmt
	checkPlaylistForUserStmt             *sql.Stmt
	checkVideoStmt                       *sql.Stmt
	checkVideoInPlaylistStmt             *sql.Stmt
	checkVideoInWatchlatersStmt          *sql.Stmt
	deleteAllPlaylistsForUserStmt        *sql.Stmt
	deleteAllVideosForUserStmt           *sql.Stmt
	deleteAllWatchlatersForUserStmt      *sql.Stmt
	deleteFromWatchlatersStmt            *sql.Stmt
	deletePlaylistStmt                   *sql.Stmt
	deleteVdieoByIdForUserStmt           *sql.Stmt
	deleteVideoFromPlaylistStmt          *sql.Stmt
	getAllPlaylistsForUserStmt           *sql.Stmt
	getAllVideosForUserStmt              *sql.Stmt
	getAllVideosInPlaylistStmt           *sql.Stmt
	getAllVideosInWatchlatersForUserStmt *sql.Stmt
	getPlaylistForUserStmt               *sql.Stmt
	getVideoByIdStmt                     *sql.Stmt
	insertIntoPlaylistStmt               *sql.Stmt
	insertIntoWatchlatersStmt            *sql.Stmt
	insertPlaylistStmt                   *sql.Stmt
	insertVideoStmt                      *sql.Stmt
	updateVideoStatusStmt                *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                   tx,
		tx:                                   tx,
		checkPlaylistStmt:                    q.checkPlaylistStmt,
		checkPlaylistByNameForUserStmt:       q.checkPlaylistByNameForUserStmt,
		checkPlaylistForUserStmt:             q.checkPlaylistForUserStmt,
		checkVideoStmt:                       q.checkVideoStmt,
		checkVideoInPlaylistStmt:             q.checkVideoInPlaylistStmt,
		checkVideoInWatchlatersStmt:          q.checkVideoInWatchlatersStmt,
		deleteAllPlaylistsForUserStmt:        q.deleteAllPlaylistsForUserStmt,
		deleteAllVideosForUserStmt:           q.deleteAllVideosForUserStmt,
		deleteAllWatchlatersForUserStmt:      q.deleteAllWatchlatersForUserStmt,
		deleteFromWatchlatersStmt:            q.deleteFromWatchlatersStmt,
		deletePlaylistStmt:                   q.deletePlaylistStmt,
		deleteVdieoByIdForUserStmt:           q.deleteVdieoByIdForUserStmt,
		deleteVideoFromPlaylistStmt:          q.deleteVideoFromPlaylistStmt,
		getAllPlaylistsForUserStmt:           q.getAllPlaylistsForUserStmt,
		getAllVideosForUserStmt:              q.getAllVideosForUserStmt,
		getAllVideosInPlaylistStmt:           q.getAllVideosInPlaylistStmt,
		getAllVideosInWatchlatersForUserStmt: q.getAllVideosInWatchlatersForUserStmt,
		getPlaylistForUserStmt:               q.getPlaylistForUserStmt,
		getVideoByIdStmt:                     q.getVideoByIdStmt,
		insertIntoPlaylistStmt:               q.insertIntoPlaylistStmt,
		insertIntoWatchlatersStmt:            q.insertIntoWatchlatersStmt,
		insertPlaylistStmt:                   q.insertPlaylistStmt,
		insertVideoStmt:                      q.insertVideoStmt,
		updateVideoStatusStmt:                q.updateVideoStatusStmt,
	}
}
