// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type VideoServicePlaylist struct {
	Id        string
	Name      string
	OwnerId   string
	CreatedAt time.Time
}

type VideoServicePlaylistVideo struct {
	PlaylistId string
	VideoId    string
	AddedAt    time.Time
}

type VideoServiceVideo struct {
	Id          string
	OwnerId     string
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	Status      string
}

type VideoServiceWatchlater struct {
	VideoId string
	UserId  string
	AddedAt time.Time
}
