// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"
)

type VideoServiceVideo struct {
	Id          string
	ObjectKey   string
	OwnerId     string
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	Status      string
}
