// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type VideoServicePlaylist struct {
	Id        uuid.UUID
	Name      string
	OwnerId   uuid.UUID
	CreatedAt time.Time
}

type VideoServicePlaylistVideo struct {
	PlaylistId uuid.UUID
	VideoId    uuid.UUID
	AddedAt    time.Time
}

type VideoServiceVideo struct {
	Id          uuid.UUID
	OwnerId     uuid.UUID
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	Status      string
}

type VideoServiceWatchlater struct {
	VideoId uuid.UUID
	UserId  uuid.UUID
	AddedAt time.Time
}
