// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"database/sql"
)

const getVideoById = `-- name: GetVideoById :one
select id, object_key, owner_id, title, description, created_at, status from video_service.videos where id = $1 for update
`

func (q *Queries) GetVideoById(ctx context.Context, id string) (VideoServiceVideo, error) {
	row := q.queryRow(ctx, q.getVideoByIdStmt, getVideoById, id)
	var i VideoServiceVideo
	err := row.Scan(
		&i.Id,
		&i.ObjectKey,
		&i.OwnerId,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getVideoByObjectKey = `-- name: GetVideoByObjectKey :one
select id, object_key, owner_id, title, description, created_at, status from video_service.videos where object_key = $1 for update
`

func (q *Queries) GetVideoByObjectKey(ctx context.Context, objectKey string) (VideoServiceVideo, error) {
	row := q.queryRow(ctx, q.getVideoByObjectKeyStmt, getVideoByObjectKey, objectKey)
	var i VideoServiceVideo
	err := row.Scan(
		&i.Id,
		&i.ObjectKey,
		&i.OwnerId,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getVideosByUserId = `-- name: GetVideosByUserId :many
select id, object_key, owner_id, title, description, created_at, status from video_service.videos where owner_id = $1
`

func (q *Queries) GetVideosByUserId(ctx context.Context, ownerID string) ([]VideoServiceVideo, error) {
	rows, err := q.query(ctx, q.getVideosByUserIdStmt, getVideosByUserId, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoServiceVideo{}
	for rows.Next() {
		var i VideoServiceVideo
		if err := rows.Scan(
			&i.Id,
			&i.ObjectKey,
			&i.OwnerId,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertVideo = `-- name: InsertVideo :exec
insert into video_service.videos (id, object_key, owner_id, title, description, status) values ($1, $2, $3, $4, $5, $6)
`

type InsertVideoParams struct {
	Id          string
	ObjectKey   string
	OwnerId     string
	Title       string
	Description sql.NullString
	Status      string
}

func (q *Queries) InsertVideo(ctx context.Context, arg InsertVideoParams) error {
	_, err := q.exec(ctx, q.insertVideoStmt, insertVideo,
		arg.Id,
		arg.ObjectKey,
		arg.OwnerId,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	return err
}

const updateVideoStatus = `-- name: UpdateVideoStatus :exec
update video_service.videos
set status = $1
where id = $2
`

type UpdateVideoStatusParams struct {
	Status string
	Id     string
}

func (q *Queries) UpdateVideoStatus(ctx context.Context, arg UpdateVideoStatusParams) error {
	_, err := q.exec(ctx, q.updateVideoStatusStmt, updateVideoStatus, arg.Status, arg.Id)
	return err
}
