// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkPlaylist = `-- name: CheckPlaylist :one
select exists (select 1 from video_service.playlists where id = $1 for update)
`

func (q *Queries) CheckPlaylist(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.queryRow(ctx, q.checkPlaylistStmt, checkPlaylist, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPlaylistByNameForUser = `-- name: CheckPlaylistByNameForUser :one
select exists (select 1 from video_service.playlists where name = $1 and owner_id = $2 for update)
`

type CheckPlaylistByNameForUserParams struct {
	Name    string
	OwnerId uuid.UUID
}

func (q *Queries) CheckPlaylistByNameForUser(ctx context.Context, arg CheckPlaylistByNameForUserParams) (bool, error) {
	row := q.queryRow(ctx, q.checkPlaylistByNameForUserStmt, checkPlaylistByNameForUser, arg.Name, arg.OwnerId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkPlaylistForUser = `-- name: CheckPlaylistForUser :one
select exists (select 1 from video_service.playlists where id = $1 and owner_id = $2 for update)
`

type CheckPlaylistForUserParams struct {
	Id      uuid.UUID
	OwnerId uuid.UUID
}

func (q *Queries) CheckPlaylistForUser(ctx context.Context, arg CheckPlaylistForUserParams) (bool, error) {
	row := q.queryRow(ctx, q.checkPlaylistForUserStmt, checkPlaylistForUser, arg.Id, arg.OwnerId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkVideo = `-- name: CheckVideo :one
select exists (select 1 from video_service.videos where id = $1 and is_published = $2 for update)
`

type CheckVideoParams struct {
	Id          uuid.UUID
	IsPublished bool
}

func (q *Queries) CheckVideo(ctx context.Context, arg CheckVideoParams) (bool, error) {
	row := q.queryRow(ctx, q.checkVideoStmt, checkVideo, arg.Id, arg.IsPublished)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkVideoInPlaylist = `-- name: CheckVideoInPlaylist :one
select exists (select 1 from video_service.playlist_videos where playlist_id = $1 and video_id = $2 for update)
`

type CheckVideoInPlaylistParams struct {
	PlaylistId uuid.UUID
	VideoId    uuid.UUID
}

func (q *Queries) CheckVideoInPlaylist(ctx context.Context, arg CheckVideoInPlaylistParams) (bool, error) {
	row := q.queryRow(ctx, q.checkVideoInPlaylistStmt, checkVideoInPlaylist, arg.PlaylistId, arg.VideoId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const checkVideoInWatchlaters = `-- name: CheckVideoInWatchlaters :one
select exists (select 1 from video_service.watchlaters where video_id = $1 and user_id = $2 for update)
`

type CheckVideoInWatchlatersParams struct {
	VideoId uuid.UUID
	UserId  uuid.UUID
}

func (q *Queries) CheckVideoInWatchlaters(ctx context.Context, arg CheckVideoInWatchlatersParams) (bool, error) {
	row := q.queryRow(ctx, q.checkVideoInWatchlatersStmt, checkVideoInWatchlaters, arg.VideoId, arg.UserId)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAllPlaylistsForUser = `-- name: DeleteAllPlaylistsForUser :exec
delete from video_service.playlists where owner_id = $1
`

func (q *Queries) DeleteAllPlaylistsForUser(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteAllPlaylistsForUserStmt, deleteAllPlaylistsForUser, ownerID)
	return err
}

const deleteAllVideosForUser = `-- name: DeleteAllVideosForUser :many
delete from video_service.videos where owner_id = $1 returning id
`

func (q *Queries) DeleteAllVideosForUser(ctx context.Context, ownerID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.query(ctx, q.deleteAllVideosForUserStmt, deleteAllVideosForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllWatchlatersForUser = `-- name: DeleteAllWatchlatersForUser :exec
delete from video_service.watchlaters where user_id= $1
`

func (q *Queries) DeleteAllWatchlatersForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteAllWatchlatersForUserStmt, deleteAllWatchlatersForUser, userID)
	return err
}

const deleteFromWatchlaters = `-- name: DeleteFromWatchlaters :execrows
delete from video_service.watchlaters where video_id = $1 and user_id = $2
`

type DeleteFromWatchlatersParams struct {
	VideoId uuid.UUID
	UserId  uuid.UUID
}

func (q *Queries) DeleteFromWatchlaters(ctx context.Context, arg DeleteFromWatchlatersParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteFromWatchlatersStmt, deleteFromWatchlaters, arg.VideoId, arg.UserId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deletePlaylist = `-- name: DeletePlaylist :execrows
delete from video_service.playlists where id = $1 and owner_id = $2
`

type DeletePlaylistParams struct {
	Id      uuid.UUID
	OwnerId uuid.UUID
}

func (q *Queries) DeletePlaylist(ctx context.Context, arg DeletePlaylistParams) (int64, error) {
	result, err := q.exec(ctx, q.deletePlaylistStmt, deletePlaylist, arg.Id, arg.OwnerId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVideoById = `-- name: DeleteVideoById :exec
delete from video_service.videos where id = $1
`

func (q *Queries) DeleteVideoById(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.deleteVideoByIdStmt, deleteVideoById, id)
	return err
}

const deleteVideoByIdForUser = `-- name: DeleteVideoByIdForUser :execrows
delete from video_service.videos where id = $1 and owner_id = $2 and is_published = $3
`

type DeleteVideoByIdForUserParams struct {
	Id          uuid.UUID
	OwnerId     uuid.UUID
	IsPublished bool
}

func (q *Queries) DeleteVideoByIdForUser(ctx context.Context, arg DeleteVideoByIdForUserParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteVideoByIdForUserStmt, deleteVideoByIdForUser, arg.Id, arg.OwnerId, arg.IsPublished)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteVideoFromPlaylist = `-- name: DeleteVideoFromPlaylist :execrows
delete from video_service.playlist_videos where playlist_id = $1 and video_id = $2
`

type DeleteVideoFromPlaylistParams struct {
	PlaylistId uuid.UUID
	VideoId    uuid.UUID
}

func (q *Queries) DeleteVideoFromPlaylist(ctx context.Context, arg DeleteVideoFromPlaylistParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteVideoFromPlaylistStmt, deleteVideoFromPlaylist, arg.PlaylistId, arg.VideoId)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllPlaylistsForUser = `-- name: GetAllPlaylistsForUser :many
select 
  p.id,
  p.name,
  count(pv.video_id) as videos_count
from video_service.playlists p
left join video_service.playlist_videos pv on p.id = pv.playlist_id
where owner_id = $1
group by p.id
order by p.created_at desc
`

type GetAllPlaylistsForUserRow struct {
	Id          uuid.UUID
	Name        string
	VideosCount int64
}

func (q *Queries) GetAllPlaylistsForUser(ctx context.Context, ownerID uuid.UUID) ([]GetAllPlaylistsForUserRow, error) {
	rows, err := q.query(ctx, q.getAllPlaylistsForUserStmt, getAllPlaylistsForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllPlaylistsForUserRow{}
	for rows.Next() {
		var i GetAllPlaylistsForUserRow
		if err := rows.Scan(&i.Id, &i.Name, &i.VideosCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPublishedVideosForUser = `-- name: GetAllPublishedVideosForUser :many
select id, owner_id, title, description, created_at, is_published from video_service.videos where owner_id = $1 and is_published = true
`

func (q *Queries) GetAllPublishedVideosForUser(ctx context.Context, ownerID uuid.UUID) ([]VideoServiceVideo, error) {
	rows, err := q.query(ctx, q.getAllPublishedVideosForUserStmt, getAllPublishedVideosForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoServiceVideo{}
	for rows.Next() {
		var i VideoServiceVideo
		if err := rows.Scan(
			&i.Id,
			&i.OwnerId,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVideosInPlaylist = `-- name: GetAllVideosInPlaylist :many
select v.id, v.owner_id, v.title, v.description, v.created_at, v.is_published
from video_service.playlist_videos pv
join video_service.videos v on v.id = pv.video_id
where pv.playlist_id = $1
order by pv.added_at desc
`

func (q *Queries) GetAllVideosInPlaylist(ctx context.Context, playlistID uuid.UUID) ([]VideoServiceVideo, error) {
	rows, err := q.query(ctx, q.getAllVideosInPlaylistStmt, getAllVideosInPlaylist, playlistID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoServiceVideo{}
	for rows.Next() {
		var i VideoServiceVideo
		if err := rows.Scan(
			&i.Id,
			&i.OwnerId,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllVideosInWatchlatersForUser = `-- name: GetAllVideosInWatchlatersForUser :many
select v.id, v.owner_id, v.title, v.description, v.created_at, v.is_published
from video_service.watchlaters wl
join video_service.videos v on v.id = wl.video_id and v.owner_id = wl.user_id
where wl.user_id = $1
order by wl.added_at desc
`

func (q *Queries) GetAllVideosInWatchlatersForUser(ctx context.Context, userID uuid.UUID) ([]VideoServiceVideo, error) {
	rows, err := q.query(ctx, q.getAllVideosInWatchlatersForUserStmt, getAllVideosInWatchlatersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VideoServiceVideo{}
	for rows.Next() {
		var i VideoServiceVideo
		if err := rows.Scan(
			&i.Id,
			&i.OwnerId,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.IsPublished,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylistForUser = `-- name: GetPlaylistForUser :one
select
  p.id,
  p.name,
  count(pv.video_id) as videos_count
from video_service.playlists p
left join video_service.playlist_videos pv on p.id = pv.playlist_id
where p.id = $1 and p.owner_id = $2
group by p.id
`

type GetPlaylistForUserParams struct {
	Id      uuid.UUID
	OwnerId uuid.UUID
}

type GetPlaylistForUserRow struct {
	Id          uuid.UUID
	Name        string
	VideosCount int64
}

func (q *Queries) GetPlaylistForUser(ctx context.Context, arg GetPlaylistForUserParams) (GetPlaylistForUserRow, error) {
	row := q.queryRow(ctx, q.getPlaylistForUserStmt, getPlaylistForUser, arg.Id, arg.OwnerId)
	var i GetPlaylistForUserRow
	err := row.Scan(&i.Id, &i.Name, &i.VideosCount)
	return i, err
}

const getVideoById = `-- name: GetVideoById :one
select id, owner_id, title, description, created_at, is_published from video_service.videos where id = $1 for update
`

func (q *Queries) GetVideoById(ctx context.Context, id uuid.UUID) (VideoServiceVideo, error) {
	row := q.queryRow(ctx, q.getVideoByIdStmt, getVideoById, id)
	var i VideoServiceVideo
	err := row.Scan(
		&i.Id,
		&i.OwnerId,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.IsPublished,
	)
	return i, err
}

const insertIntoPlaylist = `-- name: InsertIntoPlaylist :exec
insert into video_service.playlist_videos (playlist_id, video_id) values ($1, $2)
`

type InsertIntoPlaylistParams struct {
	PlaylistId uuid.UUID
	VideoId    uuid.UUID
}

func (q *Queries) InsertIntoPlaylist(ctx context.Context, arg InsertIntoPlaylistParams) error {
	_, err := q.exec(ctx, q.insertIntoPlaylistStmt, insertIntoPlaylist, arg.PlaylistId, arg.VideoId)
	return err
}

const insertIntoWatchlaters = `-- name: InsertIntoWatchlaters :exec
insert into video_service.watchlaters (video_id, user_id) values ($1, $2)
`

type InsertIntoWatchlatersParams struct {
	VideoId uuid.UUID
	UserId  uuid.UUID
}

func (q *Queries) InsertIntoWatchlaters(ctx context.Context, arg InsertIntoWatchlatersParams) error {
	_, err := q.exec(ctx, q.insertIntoWatchlatersStmt, insertIntoWatchlaters, arg.VideoId, arg.UserId)
	return err
}

const insertPlaylist = `-- name: InsertPlaylist :exec
insert into video_service.playlists (id, name, owner_id) values ($1, $2, $3)
`

type InsertPlaylistParams struct {
	Id      uuid.UUID
	Name    string
	OwnerId uuid.UUID
}

func (q *Queries) InsertPlaylist(ctx context.Context, arg InsertPlaylistParams) error {
	_, err := q.exec(ctx, q.insertPlaylistStmt, insertPlaylist, arg.Id, arg.Name, arg.OwnerId)
	return err
}

const insertVideo = `-- name: InsertVideo :exec
insert into video_service.videos (id, owner_id, title, description) values ($1, $2, $3, $4)
`

type InsertVideoParams struct {
	Id          uuid.UUID
	OwnerId     uuid.UUID
	Title       string
	Description sql.NullString
}

func (q *Queries) InsertVideo(ctx context.Context, arg InsertVideoParams) error {
	_, err := q.exec(ctx, q.insertVideoStmt, insertVideo,
		arg.Id,
		arg.OwnerId,
		arg.Title,
		arg.Description,
	)
	return err
}

const markVideoAsPublished = `-- name: MarkVideoAsPublished :exec
update video_service.videos
set is_published = true
where id = $1
`

func (q *Queries) MarkVideoAsPublished(ctx context.Context, id uuid.UUID) error {
	_, err := q.exec(ctx, q.markVideoAsPublishedStmt, markVideoAsPublished, id)
	return err
}
