// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.checkEmailStmt, err = db.PrepareContext(ctx, checkEmail); err != nil {
		return nil, fmt.Errorf("error preparing query CheckEmail: %w", err)
	}
	if q.deleteSessionForUserStmt, err = db.PrepareContext(ctx, deleteSessionForUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteSessionForUser: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.getSessionByIDStmt, err = db.PrepareContext(ctx, getSessionByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetSessionByID: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.insertEmailVerificationTokenStmt, err = db.PrepareContext(ctx, insertEmailVerificationToken); err != nil {
		return nil, fmt.Errorf("error preparing query InsertEmailVerificationToken: %w", err)
	}
	if q.insertSessionStmt, err = db.PrepareContext(ctx, insertSession); err != nil {
		return nil, fmt.Errorf("error preparing query InsertSession: %w", err)
	}
	if q.insertUserStmt, err = db.PrepareContext(ctx, insertUser); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUser: %w", err)
	}
	if q.verifyEmailByTokenStmt, err = db.PrepareContext(ctx, verifyEmailByToken); err != nil {
		return nil, fmt.Errorf("error preparing query VerifyEmailByToken: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.checkEmailStmt != nil {
		if cerr := q.checkEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing checkEmailStmt: %w", cerr)
		}
	}
	if q.deleteSessionForUserStmt != nil {
		if cerr := q.deleteSessionForUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteSessionForUserStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.getSessionByIDStmt != nil {
		if cerr := q.getSessionByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getSessionByIDStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.insertEmailVerificationTokenStmt != nil {
		if cerr := q.insertEmailVerificationTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertEmailVerificationTokenStmt: %w", cerr)
		}
	}
	if q.insertSessionStmt != nil {
		if cerr := q.insertSessionStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertSessionStmt: %w", cerr)
		}
	}
	if q.insertUserStmt != nil {
		if cerr := q.insertUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUserStmt: %w", cerr)
		}
	}
	if q.verifyEmailByTokenStmt != nil {
		if cerr := q.verifyEmailByTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing verifyEmailByTokenStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	checkEmailStmt                   *sql.Stmt
	deleteSessionForUserStmt         *sql.Stmt
	deleteUserStmt                   *sql.Stmt
	getSessionByIDStmt               *sql.Stmt
	getUserByEmailStmt               *sql.Stmt
	insertEmailVerificationTokenStmt *sql.Stmt
	insertSessionStmt                *sql.Stmt
	insertUserStmt                   *sql.Stmt
	verifyEmailByTokenStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		checkEmailStmt:                   q.checkEmailStmt,
		deleteSessionForUserStmt:         q.deleteSessionForUserStmt,
		deleteUserStmt:                   q.deleteUserStmt,
		getSessionByIDStmt:               q.getSessionByIDStmt,
		getUserByEmailStmt:               q.getUserByEmailStmt,
		insertEmailVerificationTokenStmt: q.insertEmailVerificationTokenStmt,
		insertSessionStmt:                q.insertSessionStmt,
		insertUserStmt:                   q.insertUserStmt,
		verifyEmailByTokenStmt:           q.verifyEmailByTokenStmt,
	}
}
