// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	"github.com/google/uuid"
)

type AuthEmailVerificationToken struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type AuthSession struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	SessionToken string
	CsrfToken    string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type AuthUser struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	IsVerified   bool
}
