// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"time"

	ulid "github.com/oklog/ulid/v2"
)

type AuthEmailVerificationToken struct {
	ID        ulid.ULID
	OwnerID   ulid.ULID
	Token     string
	CreatedAt time.Time
	ExpiresAt time.Time
}

type AuthSession struct {
	ID           ulid.ULID
	OwnerID      ulid.ULID
	SessionToken string
	CsrfToken    string
	CreatedAt    time.Time
	ExpiresAt    time.Time
}

type AuthUser struct {
	ID           ulid.ULID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	IsVerified   bool
}
