// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package queries

import (
	"context"
	"time"

	ulid "github.com/oklog/ulid/v2"
)

const checkEmail = `-- name: CheckEmail :one
select exists (select 1 from auth.users where email = $1 for update)
`

func (q *Queries) CheckEmail(ctx context.Context, email string) (bool, error) {
	row := q.queryRow(ctx, q.checkEmailStmt, checkEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteSessionForUser = `-- name: DeleteSessionForUser :execrows
delete from auth.sessions where id = $1 and owner_id = $2
`

type DeleteSessionForUserParams struct {
	SessionID ulid.ULID
	UserID    ulid.ULID
}

func (q *Queries) DeleteSessionForUser(ctx context.Context, arg DeleteSessionForUserParams) (int64, error) {
	result, err := q.exec(ctx, q.deleteSessionForUserStmt, deleteSessionForUser, arg.SessionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteUser = `-- name: DeleteUser :execrows
delete from auth.users where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id ulid.ULID) (int64, error) {
	result, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByID = `-- name: GetSessionByID :one
select id, owner_id, session_token, csrf_token, created_at, expires_at from auth.sessions where id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id ulid.ULID) (AuthSession, error) {
	row := q.queryRow(ctx, q.getSessionByIDStmt, getSessionByID, id)
	var i AuthSession
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.SessionToken,
		&i.CsrfToken,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, created_at, is_verified from auth.users where email = $1 for update
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsVerified,
	)
	return i, err
}

const insertEmailVerificationToken = `-- name: InsertEmailVerificationToken :exec
insert into auth.email_verification_tokens (id, owner_id, token, expires_at)
values ($1, $2, $3, $4)
`

type InsertEmailVerificationTokenParams struct {
	ID        ulid.ULID
	OwnerID   ulid.ULID
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) InsertEmailVerificationToken(ctx context.Context, arg InsertEmailVerificationTokenParams) error {
	_, err := q.exec(ctx, q.insertEmailVerificationTokenStmt, insertEmailVerificationToken,
		arg.ID,
		arg.OwnerID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const insertSession = `-- name: InsertSession :exec
insert into auth.sessions (id, owner_id, session_token, csrf_token, expires_at)
values ($1, $2, $3, $4, $5)
`

type InsertSessionParams struct {
	ID           ulid.ULID
	OwnerID      ulid.ULID
	SessionToken string
	CsrfToken    string
	ExpiresAt    time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.exec(ctx, q.insertSessionStmt, insertSession,
		arg.ID,
		arg.OwnerID,
		arg.SessionToken,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
insert into auth.users (id, email, password_hash)
values ($1, $2, $3)
`

type InsertUserParams struct {
	ID           ulid.ULID
	Email        string
	PasswordHash string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.exec(ctx, q.insertUserStmt, insertUser, arg.ID, arg.Email, arg.PasswordHash)
	return err
}

const verifyEmailByToken = `-- name: VerifyEmailByToken :execrows
update auth.users
set is_verified = true
where id in (
  select owner_id
  from auth.email_verification_tokens evt
  where token = $1 and expires_at > now()
)
`

func (q *Queries) VerifyEmailByToken(ctx context.Context, token string) (int64, error) {
	result, err := q.exec(ctx, q.verifyEmailByTokenStmt, verifyEmailByToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
