// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.deleteExpiredUploadsStmt, err = db.PrepareContext(ctx, deleteExpiredUploads); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredUploads: %w", err)
	}
	if q.deleteObjectKeyForVideoStmt, err = db.PrepareContext(ctx, deleteObjectKeyForVideo); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteObjectKeyForVideo: %w", err)
	}
	if q.deleteObjectKeysInListStmt, err = db.PrepareContext(ctx, deleteObjectKeysInList); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteObjectKeysInList: %w", err)
	}
	if q.deleteUploadStmt, err = db.PrepareContext(ctx, deleteUpload); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUpload: %w", err)
	}
	if q.getObjectKeyForVideoStmt, err = db.PrepareContext(ctx, getObjectKeyForVideo); err != nil {
		return nil, fmt.Errorf("error preparing query GetObjectKeyForVideo: %w", err)
	}
	if q.getUploadIdForObjectStmt, err = db.PrepareContext(ctx, getUploadIdForObject); err != nil {
		return nil, fmt.Errorf("error preparing query GetUploadIdForObject: %w", err)
	}
	if q.insertObjectKeyStmt, err = db.PrepareContext(ctx, insertObjectKey); err != nil {
		return nil, fmt.Errorf("error preparing query InsertObjectKey: %w", err)
	}
	if q.insertUploadStmt, err = db.PrepareContext(ctx, insertUpload); err != nil {
		return nil, fmt.Errorf("error preparing query InsertUpload: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.deleteExpiredUploadsStmt != nil {
		if cerr := q.deleteExpiredUploadsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredUploadsStmt: %w", cerr)
		}
	}
	if q.deleteObjectKeyForVideoStmt != nil {
		if cerr := q.deleteObjectKeyForVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteObjectKeyForVideoStmt: %w", cerr)
		}
	}
	if q.deleteObjectKeysInListStmt != nil {
		if cerr := q.deleteObjectKeysInListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteObjectKeysInListStmt: %w", cerr)
		}
	}
	if q.deleteUploadStmt != nil {
		if cerr := q.deleteUploadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUploadStmt: %w", cerr)
		}
	}
	if q.getObjectKeyForVideoStmt != nil {
		if cerr := q.getObjectKeyForVideoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getObjectKeyForVideoStmt: %w", cerr)
		}
	}
	if q.getUploadIdForObjectStmt != nil {
		if cerr := q.getUploadIdForObjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUploadIdForObjectStmt: %w", cerr)
		}
	}
	if q.insertObjectKeyStmt != nil {
		if cerr := q.insertObjectKeyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertObjectKeyStmt: %w", cerr)
		}
	}
	if q.insertUploadStmt != nil {
		if cerr := q.insertUploadStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertUploadStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                          DBTX
	tx                          *sql.Tx
	deleteExpiredUploadsStmt    *sql.Stmt
	deleteObjectKeyForVideoStmt *sql.Stmt
	deleteObjectKeysInListStmt  *sql.Stmt
	deleteUploadStmt            *sql.Stmt
	getObjectKeyForVideoStmt    *sql.Stmt
	getUploadIdForObjectStmt    *sql.Stmt
	insertObjectKeyStmt         *sql.Stmt
	insertUploadStmt            *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                          tx,
		tx:                          tx,
		deleteExpiredUploadsStmt:    q.deleteExpiredUploadsStmt,
		deleteObjectKeyForVideoStmt: q.deleteObjectKeyForVideoStmt,
		deleteObjectKeysInListStmt:  q.deleteObjectKeysInListStmt,
		deleteUploadStmt:            q.deleteUploadStmt,
		getObjectKeyForVideoStmt:    q.getObjectKeyForVideoStmt,
		getUploadIdForObjectStmt:    q.getUploadIdForObjectStmt,
		insertObjectKeyStmt:         q.insertObjectKeyStmt,
		insertUploadStmt:            q.insertUploadStmt,
	}
}
