// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type MediaServiceUpload struct {
	Id          string
	VideoId     uuid.UUID
	ExpiresAt   time.Time
	CompletedAt sql.NullTime
}

type MediaServiceVideo struct {
	Id        uuid.UUID
	ObjectKey string
	Status    string
}
