// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"time"

	"github.com/google/uuid"
)

type MediaServiceObjectKey struct {
	VideoId   uuid.UUID
	ObjectKey string
}

type MediaServiceUpload struct {
	Id        string
	ObjectKey string
	ExpiresAt time.Time
}
