// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const x = `-- name: X :one
select 1
`

func (q *Queries) X(ctx context.Context) (int32, error) {
	row := q.queryRow(ctx, q.xStmt, x)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
