// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package queries

import (
	"context"
)

const getObjectKeyForVideo = `-- name: GetObjectKeyForVideo :one
select object_key from media_service.object_keys where video_id = $1
`

func (q *Queries) GetObjectKeyForVideo(ctx context.Context, videoID string) (string, error) {
	row := q.queryRow(ctx, q.getObjectKeyForVideoStmt, getObjectKeyForVideo, videoID)
	var object_key string
	err := row.Scan(&object_key)
	return object_key, err
}

const insertObjectKey = `-- name: InsertObjectKey :exec
insert into media_service.object_keys (video_id, object_key) values ($1, $2)
`

type InsertObjectKeyParams struct {
	VideoId   string
	ObjectKey string
}

func (q *Queries) InsertObjectKey(ctx context.Context, arg InsertObjectKeyParams) error {
	_, err := q.exec(ctx, q.insertObjectKeyStmt, insertObjectKey, arg.VideoId, arg.ObjectKey)
	return err
}
